### ISSUE TITLE
Make Travis faster

### ISSUE THREAD

**Issue by wavebeem** [jneen/parsimmon#223]
Adding this snippet to `.travis.yml` should speed up Travis by caching our dependencies

```yml
sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - "node"
  - "lts/*"
cache:
  directories:
    - "$HOME/.npm"
install:
  - npm ci
script:
  - npm test
```

Will also need to add a `before_install` to install a modern npm version if we wanna cover Node versions without npm ci support.
